// Port of shared-world-helper/internal/savefile tests + Go/C++ conformance.
#include <atomic>
#include <chrono>
#include <thread>

#include "SharedWorldCore/Save/SaveFile.h"
#include "SharedWorldCore/Util/FileUtil.h"
#include "SharedWorldCore/Util/Json.h"
#include "SharedWorldCore/Util/Random.h"
#include "TestFramework.h"

using namespace sw;

namespace
{
	std::string RandomBytes(size_t N)
	{
		SeededRandom R(1);
		std::string Hex = R.Hex(N);
		std::string Out(N, '\0');
		for (size_t i = 0; i < N; ++i) Out[i] = static_cast<char>(std::stoi(Hex.substr(i * 2, 2), nullptr, 16));
		return Out;
	}
}

// The C++ validator must reach the Go reference validator's verdict on
// every file of the corpus (generated by shared-world-helper/tools/conformance).
SW_TEST(Save_ConformanceWithGoReference)
{
	const std::string Dir = std::string(SW_TESTDATA_DIR) + "/conformance";
	auto Expected = file::ReadAll(file::Join(Dir, "expected.json"));
	ASSERT_OK(Expected);
	auto V = json::Parse(*Expected);
	ASSERT_OK(V);
	int Checked = 0;
	for (const auto& [Name, Verdict] : V->AsObject())
	{
		const bool bWantValid = Verdict.Find("valid")->AsBool();
		auto Got = save::ValidateFile(file::Join(Dir, Name));
		++Checked;
		if (Got.Ok() != bWantValid)
		{
			swtest::ReportFailure(__FILE__, __LINE__, Name + ": Go says " + (bWantValid ? "valid" : "invalid") + ", C++ says " +
				(Got.Ok() ? "valid" : "invalid (" + Got.Err().Describe() + ")"));
			continue;
		}
		if (Got.Ok())
		{
			EXPECT_EQ(Got->SessionName, Verdict.Find("sessionName")->AsString());
			EXPECT_EQ(Got->MapName, Verdict.Find("mapName")->AsString());
		}
		else if (!Got.Is(ErrorCode::Corrupt))
		{
			swtest::ReportFailure(__FILE__, __LINE__, Name + ": damaged saves must be Corrupt, got " + Got.Err().Describe());
		}
	}
	EXPECT_TRUE(Checked >= 20);
}

SW_TEST(Save_AcceptsValidSynthetic)
{
	const std::string Body = RandomBytes(400000); // spans several chunks
	auto H = save::ValidateBytes(save::BuildSynthetic("MyFactory", Body));
	ASSERT_OK(H);
	EXPECT_EQ(H->SessionName, std::string("MyFactory"));
	EXPECT_EQ(H->SaveName, std::string("MyFactory"));
	EXPECT_EQ(H->MapName, std::string("Persistent_Level"));
}

SW_TEST(Save_RejectsTruncatedCorruptAndGarbage)
{
	std::string Body;
	for (int i = 0; i < 100000; ++i) Body += "factory";
	const std::string Full = save::BuildSynthetic("S", Body);
	for (size_t Cut : {Full.size() - 1, Full.size() - 1000, Full.size() / 2, size_t(200)})
	{
		if (save::ValidateBytes(Full.substr(0, Cut)).Ok())
			swtest::ReportFailure(__FILE__, __LINE__, "truncated save accepted at " + std::to_string(Cut));
	}
	std::string Flipped = Full;
	Flipped[Flipped.size() - 10] = static_cast<char>(~Flipped[Flipped.size() - 10]); // flip every bit
	EXPECT_ERR(save::ValidateBytes(Flipped), ErrorCode::Corrupt);
	EXPECT_ERR(save::ValidateBytes(RandomBytes(5000)), ErrorCode::Corrupt);
}

SW_TEST(Save_ValidateSaveName)
{
	for (const char* Bad : {"", "../x", "a/b", "a\\b", "x.sav", "con:", "a b"})
	{
		if (save::ValidateSaveName(Bad).Ok()) swtest::ReportFailure(__FILE__, __LINE__, std::string("accepted: ") + Bad);
	}
	ASSERT_OK(save::ValidateSaveName("SharedWorld_our-factory"));
}

SW_TEST(Save_WaitStableWaitsForWriterToFinish)
{
	const std::string P = file::Join(swtest::TempDir(), "w.sav");
	ASSERT_OK(file::WriteAtomic(P, "a"));
	std::atomic<bool> Done{false};
	std::thread Writer([&]()
	{
		std::string Data = "a";
		for (int i = 0; i < 8; ++i)
		{
			std::this_thread::sleep_for(std::chrono::milliseconds(25));
			Data += std::string(1000, 'x');
			(void)file::WriteAtomic(P, Data);
		}
		Done = true;
	});
	ASSERT_OK(save::WaitStable(P, 120, 10000));
	EXPECT_TRUE(Done.load()); // did not return while the file was still changing
	Writer.join();
	EXPECT_EQ(file::Size(P).Value(), int64_t(8001));
}

SW_TEST(Save_MapLabelAndPlayDurationFormatting)
{
	EXPECT_EQ(save::MapLabelFromOptions("?startloc=Grass Fields"), std::string("Grass Fields"));
	EXPECT_EQ(save::MapLabelFromOptions("startloc=Rocky Desert&foo=1"), std::string("Rocky Desert"));
	EXPECT_EQ(save::MapLabelFromOptions("?startloc=Dune%20Desert"), std::string("Dune Desert"));
	EXPECT_EQ(save::MapLabelFromOptions(""), std::string());
	EXPECT_EQ(save::FormatPlayDuration(0), std::string());
	EXPECT_EQ(save::FormatPlayDuration(45), std::string("45s"));
	EXPECT_EQ(save::FormatPlayDuration(125), std::string("2m"));
	EXPECT_EQ(save::FormatPlayDuration(87 * 3600 + 22 * 60), std::string("87h 22m"));

	save::SaveHeader H;
	H.MapOptions = "?startloc=Grass Fields";
	H.PlayDurationSeconds = 90;
	EXPECT_EQ(H.MapLabel(), std::string("Grass Fields"));
}
